# Generated by Django 3.0.6 on 2020-05-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_secret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Secret',
        ),
    ]
