# Generated by Django 3.0.6 on 2020-05-11 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_delete_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('secret_key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pass_phrase', models.CharField(max_length=90, verbose_name='Pass')),
                ('text', models.TextField(max_length=1000, verbose_name='text')),
                ('life_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
