# Generated by Django 3.0.6 on 2020-05-12 15:05

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200512_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='text',
            field=django_cryptography.fields.encrypt(models.TextField(max_length=1000, verbose_name='text')),
        ),
    ]
