# Generated by Django 3.0.6 on 2020-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200512_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='text'),
        ),
    ]
