# Generated by Django 3.0.6 on 2020-05-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200512_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='pass_phrase',
            field=models.CharField(max_length=200, verbose_name='Pass'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='text',
            field=models.TextField(max_length=200, verbose_name='text'),
        ),
    ]
