# Generated by Django 3.0.6 on 2020-05-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200513_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='pass_phrase',
            field=models.BinaryField(max_length=200, verbose_name='Pass'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='text',
            field=models.BinaryField(max_length=200, verbose_name='text'),
        ),
    ]
