# Generated by Django 3.0.6 on 2020-05-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200513_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='pass_phrase',
            field=models.CharField(max_length=200, verbose_name='Pass'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='text',
            field=models.TextField(max_length=200, verbose_name='text'),
        ),
    ]
